//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_base_flutter/src/ios/ios.export.g.dart';
import 'package:amap_base_flutter/src/android/android.export.g.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
class MACustomBuildingOverlayRenderer extends MAOverlayRenderer  {
  // generate getters
  Future<MACustomBuildingOverlay> get_customBuildingOverlay() async {
    final result = await MethodChannel('me.yohom/amap_base_flutter').invokeMethod("MACustomBuildingOverlayRenderer::get_customBuildingOverlay", {'refId': refId});
    kNativeObjectPool.add(MACustomBuildingOverlay()..refId = result..tag = 'amap_base_flutter');
    return MACustomBuildingOverlay()..refId = result..tag = 'amap_base_flutter';
  }
  

  // generate setters
  

  // generate methods
  Future<MACustomBuildingOverlayRenderer> initWithCustomBuildingOverlay(MACustomBuildingOverlay customBuildingOverlay) async {
    // print log
    print('fluttify-dart: MACustomBuildingOverlayRenderer@$refId::initWithCustomBuildingOverlay([])');
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_base_flutter').invokeMethod('MACustomBuildingOverlayRenderer::initWithCustomBuildingOverlay', {"customBuildingOverlay": customBuildingOverlay.refId, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(MACustomBuildingOverlayRenderer()..refId = result..tag = 'amap_base_flutter');
      return MACustomBuildingOverlayRenderer()..refId = result..tag = 'amap_base_flutter';
    }
  }
  
}