//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_base_flutter/src/ios/ios.export.g.dart';
import 'package:amap_base_flutter/src/android/android.export.g.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
class MAOfflineProvince extends MAOfflineItem  {
  // generate getters
  Future<List> get_cities() async {
    final result = await MethodChannel('me.yohom/amap_base_flutter').invokeMethod("MAOfflineProvince::get_cities", {'refId': refId});
    kNativeObjectPool.addAll((result as List).cast<int>().map((it) => NSObject()..refId = it..tag = 'amap_base_flutter').toList());
    return (result as List).cast<int>().map((it) => NSObject()..refId = it..tag = 'amap_base_flutter').toList();
  }
  

  // generate setters
  

  // generate methods
  
}