//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_base_flutter/src/ios/ios.export.g.dart';
import 'package:amap_base_flutter/src/android/android.export.g.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
class MATileOverlayRenderer extends MAOverlayRenderer  {
  // generate getters
  Future<MATileOverlay> get_tileOverlay() async {
    final result = await MethodChannel('me.yohom/amap_base_flutter').invokeMethod("MATileOverlayRenderer::get_tileOverlay", {'refId': refId});
    kNativeObjectPool.add(MATileOverlay()..refId = result..tag = 'amap_base_flutter');
    return MATileOverlay()..refId = result..tag = 'amap_base_flutter';
  }
  

  // generate setters
  

  // generate methods
  Future<MATileOverlayRenderer> initWithTileOverlay(MATileOverlay tileOverlay) async {
    // print log
    print('fluttify-dart: MATileOverlayRenderer@$refId::initWithTileOverlay([])');
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_base_flutter').invokeMethod('MATileOverlayRenderer::initWithTileOverlay', {"tileOverlay": tileOverlay.refId, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(MATileOverlayRenderer()..refId = result..tag = 'amap_base_flutter');
      return MATileOverlayRenderer()..refId = result..tag = 'amap_base_flutter';
    }
  }
  
  Future<void> reloadData() async {
    // print log
    print('fluttify-dart: MATileOverlayRenderer@$refId::reloadData([])');
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_base_flutter').invokeMethod('MATileOverlayRenderer::reloadData', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
}