// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_map_fluttify/src/ios/ios.export.g.dart';
import 'package:amap_map_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';

class AMapServices extends NSObject  {
  //region constants
  
  //endregion

  //region creators
  static Future<AMapServices> create__() async {
    final int refId = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('ObjectFactory::createAMapServices');
    final object = AMapServices()..refId = refId..tag = 'amap_map_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<AMapServices>> create_batch__(int length) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('ObjectFactory::create_batchAMapServices', {'length': length});
  
    final List<AMapServices> typedResult = resultBatch.map((result) => AMapServices()..refId = result..tag = 'amap_map_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  Future<String> get_apiKey() async {
    final result = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapServices::get_apiKey", {'refId': refId});
  
    return result;
  }
  
  Future<bool> get_enableHTTPS() async {
    final result = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapServices::get_enableHTTPS", {'refId': refId});
  
    return result;
  }
  
  Future<bool> get_crashReportEnabled() async {
    final result = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapServices::get_crashReportEnabled", {'refId': refId});
  
    return result;
  }
  
  Future<String> get_identifier() async {
    final result = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapServices::get_identifier", {'refId': refId});
  
    return result;
  }
  
  //endregion

  //region setters
  Future<void> set_apiKey(String apiKey) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapServices::set_apiKey', {'refId': refId, "apiKey": apiKey});
  
  
  }
  
  Future<void> set_enableHTTPS(bool enableHTTPS) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapServices::set_enableHTTPS', {'refId': refId, "enableHTTPS": enableHTTPS});
  
  
  }
  
  Future<void> set_crashReportEnabled(bool crashReportEnabled) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapServices::set_crashReportEnabled', {'refId': refId, "crashReportEnabled": crashReportEnabled});
  
  
  }
  
  //endregion

  //region methods
  static Future<AMapServices> sharedServices() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: AMapServices::sharedServices([])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapServices::sharedServices', );
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(AMapServices()..refId = result..tag = 'amap_map_fluttify');
      return AMapServices()..refId = result..tag = 'amap_map_fluttify';
    }
  }
  
  //endregion
}

extension AMapServices_Batch on List<AMapServices> {
  //region getters
  Future<List<String>> get_apiKey_batch() async {
    final resultBatch = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapServices::get_apiKey_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<bool>> get_enableHTTPS_batch() async {
    final resultBatch = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapServices::get_enableHTTPS_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<bool>> get_crashReportEnabled_batch() async {
    final resultBatch = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapServices::get_crashReportEnabled_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<String>> get_identifier_batch() async {
    final resultBatch = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapServices::get_identifier_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  //endregion

  //region setters
  Future<void> set_apiKey_batch(List<String> apiKey) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapServices::set_apiKey_batch', [for (int i = 0; i < this.length; i++) {'refId': this[i].refId, "apiKey": apiKey[i]}]);
  
  
  }
  
  Future<void> set_enableHTTPS_batch(List<bool> enableHTTPS) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapServices::set_enableHTTPS_batch', [for (int i = 0; i < this.length; i++) {'refId': this[i].refId, "enableHTTPS": enableHTTPS[i]}]);
  
  
  }
  
  Future<void> set_crashReportEnabled_batch(List<bool> crashReportEnabled) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapServices::set_crashReportEnabled_batch', [for (int i = 0; i < this.length; i++) {'refId': this[i].refId, "crashReportEnabled": crashReportEnabled[i]}]);
  
  
  }
  
  //endregion

  //region methods
  Future<List<AMapServices>> sharedServices_batch() async {
    if (false) {
      return Future.error('all args must have same length!');
    }
  
    // invoke native method
    final resultBatch = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapServices::sharedServices_batch', [for (int i = 0; i < this.length; i++) {"refId": this[i].refId}]);
  
  
    // convert native result to dart side object
    if (resultBatch == null) {
      return null;
    } else {
      final typedResult = (resultBatch as List).map((result) => AMapServices()..refId = result..tag = 'amap_map_fluttify').toList();
      kNativeObjectPool.addAll(typedResult);
      return typedResult;
    }
  }
  
  //endregion
}