// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_map_fluttify/src/ios/ios.export.g.dart';
import 'package:amap_map_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';

class AMapRouteConfig extends NSObject  {
  //region constants
  
  //endregion

  //region creators
  static Future<AMapRouteConfig> create__() async {
    final int refId = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('ObjectFactory::createAMapRouteConfig');
    final object = AMapRouteConfig()..refId = refId..tag = 'amap_map_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<AMapRouteConfig>> create_batch__(int length) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('ObjectFactory::create_batchAMapRouteConfig', {'length': length});
  
    final List<AMapRouteConfig> typedResult = resultBatch.map((result) => AMapRouteConfig()..refId = result..tag = 'amap_map_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  Future<String> get_appScheme() async {
    final result = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapRouteConfig::get_appScheme", {'refId': refId});
  
    return result;
  }
  
  Future<String> get_appName() async {
    final result = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapRouteConfig::get_appName", {'refId': refId});
  
    return result;
  }
  
  Future<CLLocationCoordinate2D> get_startCoordinate() async {
    final result = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapRouteConfig::get_startCoordinate", {'refId': refId});
    kNativeObjectPool.add(CLLocationCoordinate2D()..refId = result..tag = 'amap_map_fluttify');
    return CLLocationCoordinate2D()..refId = result..tag = 'amap_map_fluttify';
  }
  
  Future<CLLocationCoordinate2D> get_destinationCoordinate() async {
    final result = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapRouteConfig::get_destinationCoordinate", {'refId': refId});
    kNativeObjectPool.add(CLLocationCoordinate2D()..refId = result..tag = 'amap_map_fluttify');
    return CLLocationCoordinate2D()..refId = result..tag = 'amap_map_fluttify';
  }
  
  Future<AMapDrivingStrategy> get_drivingStrategy() async {
    final result = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapRouteConfig::get_drivingStrategy", {'refId': refId});
  
    return AMapDrivingStrategy.values[result];
  }
  
  Future<AMapTransitStrategy> get_transitStrategy() async {
    final result = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapRouteConfig::get_transitStrategy", {'refId': refId});
  
    return AMapTransitStrategy.values[result];
  }
  
  Future<AMapRouteSearchType> get_routeType() async {
    final result = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapRouteConfig::get_routeType", {'refId': refId});
  
    return AMapRouteSearchType.values[result];
  }
  
  //endregion

  //region setters
  Future<void> set_appScheme(String appScheme) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapRouteConfig::set_appScheme', {'refId': refId, "appScheme": appScheme});
  
  
  }
  
  Future<void> set_appName(String appName) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapRouteConfig::set_appName', {'refId': refId, "appName": appName});
  
  
  }
  
  Future<void> set_startCoordinate(CLLocationCoordinate2D startCoordinate) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapRouteConfig::set_startCoordinate', {'refId': refId, "startCoordinate": startCoordinate.refId});
  
  
  }
  
  Future<void> set_destinationCoordinate(CLLocationCoordinate2D destinationCoordinate) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapRouteConfig::set_destinationCoordinate', {'refId': refId, "destinationCoordinate": destinationCoordinate.refId});
  
  
  }
  
  Future<void> set_drivingStrategy(AMapDrivingStrategy drivingStrategy) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapRouteConfig::set_drivingStrategy', {'refId': refId, "drivingStrategy": drivingStrategy.index});
  
  
  }
  
  Future<void> set_transitStrategy(AMapTransitStrategy transitStrategy) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapRouteConfig::set_transitStrategy', {'refId': refId, "transitStrategy": transitStrategy.index});
  
  
  }
  
  Future<void> set_routeType(AMapRouteSearchType routeType) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapRouteConfig::set_routeType', {'refId': refId, "routeType": routeType.index});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}

extension AMapRouteConfig_Batch on List<AMapRouteConfig> {
  //region getters
  Future<List<String>> get_appScheme_batch() async {
    final resultBatch = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapRouteConfig::get_appScheme_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<String>> get_appName_batch() async {
    final resultBatch = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapRouteConfig::get_appName_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<CLLocationCoordinate2D>> get_startCoordinate_batch() async {
    final resultBatch = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapRouteConfig::get_startCoordinate_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => CLLocationCoordinate2D()..refId = result..tag = 'amap_map_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  Future<List<CLLocationCoordinate2D>> get_destinationCoordinate_batch() async {
    final resultBatch = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapRouteConfig::get_destinationCoordinate_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => CLLocationCoordinate2D()..refId = result..tag = 'amap_map_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  Future<List<AMapDrivingStrategy>> get_drivingStrategy_batch() async {
    final resultBatch = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapRouteConfig::get_drivingStrategy_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => AMapDrivingStrategy.values[result]).toList();
  
    return typedResult;
  }
  
  Future<List<AMapTransitStrategy>> get_transitStrategy_batch() async {
    final resultBatch = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapRouteConfig::get_transitStrategy_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => AMapTransitStrategy.values[result]).toList();
  
    return typedResult;
  }
  
  Future<List<AMapRouteSearchType>> get_routeType_batch() async {
    final resultBatch = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod("AMapRouteConfig::get_routeType_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => AMapRouteSearchType.values[result]).toList();
  
    return typedResult;
  }
  
  //endregion

  //region setters
  Future<void> set_appScheme_batch(List<String> appScheme) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapRouteConfig::set_appScheme_batch', [for (int i = 0; i < this.length; i++) {'refId': this[i].refId, "appScheme": appScheme[i]}]);
  
  
  }
  
  Future<void> set_appName_batch(List<String> appName) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapRouteConfig::set_appName_batch', [for (int i = 0; i < this.length; i++) {'refId': this[i].refId, "appName": appName[i]}]);
  
  
  }
  
  Future<void> set_startCoordinate_batch(List<CLLocationCoordinate2D> startCoordinate) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapRouteConfig::set_startCoordinate_batch', [for (int i = 0; i < this.length; i++) {'refId': this[i].refId, "startCoordinate": startCoordinate[i].refId}]);
  
  
  }
  
  Future<void> set_destinationCoordinate_batch(List<CLLocationCoordinate2D> destinationCoordinate) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapRouteConfig::set_destinationCoordinate_batch', [for (int i = 0; i < this.length; i++) {'refId': this[i].refId, "destinationCoordinate": destinationCoordinate[i].refId}]);
  
  
  }
  
  Future<void> set_drivingStrategy_batch(List<AMapDrivingStrategy> drivingStrategy) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapRouteConfig::set_drivingStrategy_batch', [for (int i = 0; i < this.length; i++) {'refId': this[i].refId, "drivingStrategy": drivingStrategy[i].index}]);
  
  
  }
  
  Future<void> set_transitStrategy_batch(List<AMapTransitStrategy> transitStrategy) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapRouteConfig::set_transitStrategy_batch', [for (int i = 0; i < this.length; i++) {'refId': this[i].refId, "transitStrategy": transitStrategy[i].index}]);
  
  
  }
  
  Future<void> set_routeType_batch(List<AMapRouteSearchType> routeType) async {
    await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('AMapRouteConfig::set_routeType_batch', [for (int i = 0; i < this.length; i++) {'refId': this[i].refId, "routeType": routeType[i].index}]);
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}