// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum AMapCoordinateType {
  AMapCoordinateTypeAMap,
  AMapCoordinateTypeBaidu,
  AMapCoordinateTypeMapBar,
  AMapCoordinateTypeMapABC,
  AMapCoordinateTypeSoSoMap,
  AMapCoordinateTypeAliYun,
  AMapCoordinateTypeGoogle,
  AMapCoordinateTypeGPS
}